{{- if (or (eq .Values.environment "build") (eq .Values.environment "combined")) }}
apiVersion: {{ include "apiVersion" . }}
kind: ImageStream
metadata:
  name: openshift-api-group
{{ include "openshift-api-group.labels" . | indent 2 }}
{{- end }}
