{{- if eq .Release.Namespace "kube-system" }}
apiVersion: {{ include "apiVersion" . }}
kind: RoleBinding
metadata:
  name: system:image-pullers
{{ include "openshift-api-group.labels" . | indent 2 }}
roleRef:
  name: system:image-puller
subjects:
- kind: SystemGroup
  name: system:serviceaccounts:{{ .Release.Namespace }}
groupNames:
- system:serviceaccounts:{{ .Release.Namespace }}
userNames: null
{{- end }}
