{{- if (or (eq .Values.environment "combined") (eq .Values.environment "deploy")) }}
apiVersion: {{ include "apiVersion" . }}
kind: RoleBinding
metadata:
  name: tiller-admin
{{ include "openshift-api-group.labels" . | indent 2 }}
subjects:
- kind: ServiceAccount
  name: tiller
roleRef:
  name: admin
{{- end }}
