{{- if .Values.clusterAdmin }}
apiVersion: {{ include "apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: tiller-cluster-admin
{{ include "openshift-api-group.labels" . | indent 2 }}
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: {{ .Release.Namespace }}
roleRef:
  name: cluster-admin
{{- end }}
