{{- if eq .Release.Namespace "kube-system" }}
apiVersion: {{ include "apiVersion" . }}
kind: RoleBinding
metadata:
  name: system:image-builders
{{ include "openshift-api-group.labels" . | indent 2 }}
roleRef:
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: builder
groupNames: null
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:builder
{{- end }}
