{{- if (or (eq .Values.environment "combined") (eq .Values.environment "deploy")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
{{ include "openshift-api-group.labels" . | indent 2 }}
{{- end }}
