{{- if (or (eq .Values.environment "combined") (eq .Values.environment "deploy")) }}
apiVersion: v1
kind: Service
metadata:
  name: tiller
spec:
  ports:
  - name: tiller
    port: 44134
    protocol: TCP
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: ClusterIP
{{- end }}
